#!/usr/bin/perl

use strict;
use warnings;

use Net::MQTT::Simple;
use JSON qw( decode_json );
use Data::Dumper;

# Establish connection to MQTT broker
my $mqtt = Net::MQTT::Simple->new('mosquitto.lan:1883');

# Subscribe to topics
#$mqtt->subscribe("shellypro1pm-xxxxxxxxxxxx/status/#", \&received);
$mqtt->subscribe("shellypro1pm-xxxxxxxxxxxx/#", \&received);
$mqtt->subscribe("shellypro1pm-xxxxxxxxxxxx/#", \&received);
$mqtt->subscribe("shelly/+/#", \&received);

my %nicknames = (
	"xxxxxxxxxxxx" => 'device-1',
	"yyyyyyyyyyyy" => 'device-2',
);
 
# Run loop
$mqtt->run();

# Disconnect (but when?)
$mqtt->disconnect();

# Receive message
sub received
{
    my ($topic, $payload) = @_;

    if ( $topic =~ m{^(?:shelly/)?shelly(.*?)-([[:xdigit:]]{12})/events/rpc$} ) {
        my $shelly_model = $1;
        my $shelly_serial = $2;
	
        my $nickname = $nicknames{ $shelly_serial };

        my $json = decode_json( $payload );

        print Dumper $json;

        my @output;

        if ( $json->{"method"} eq "NotifyStatus"  and  $json->{"params"}->{"switch:0"} ) {

            foreach ( keys %{ $json->{"params"}->{"switch:0"} } ) {
                print ref $json->{"params"}->{"switch:0"}->{ $_ };
                # No reference?
                if ( ! ref $json->{"params"}->{"switch:0"}->{ $_ } ) {
                    #TODO: Skip 'source' => 'http'
                    #TODO: 'output' missing
                    push @output, "$_=" . $json->{"params"}->{"switch:0"}->{$_};
                }
            }
            #push @output, "apower=" . $json->{"params"}->{"switch:0"}->{"apower"};
            #push @output, "freq=" . $json->{"params"}->{"switch:0"}->{"freq"};
            #push @output, "current=" . $json->{"params"}->{"switch:0"}->{"current"};
            #push @output, "voltage=" . $json->{"params"}->{"switch:0"}->{"voltage"};
            #push @output, "pf=" . $json->{"params"}->{"switch:0"}->{"pf"};
            #push @output, "aprtpower=" . $json->{"params"}->{"switch:0"}->{"aprtpower"};
            if ( $json->{"params"}->{"switch:0"}->{"aenergy"} ) {
                push @output, "aenergy_total=" . $json->{"params"}->{"switch:0"}->{"aenergy"}->{"total"};
                my $arrayindex = 0;
                foreach ( @{ $json->{"params"}->{"switch:0"}->{"aenergy"}->{"by_minute"} } ) {
                    push @output, "aenergy_by_minute_$arrayindex=$_";
                    $arrayindex++;
                }
            }
            if ( $json->{"params"}->{"switch:0"}->{"ret_aenergy"} ) {
                push @output, "ret_aenergy_total=" . $json->{"params"}->{"switch:0"}->{"ret_aenergy"}->{"total"};
                my $arrayindex = 0;
                foreach ( @{ $json->{"params"}->{"switch:0"}->{"ret_aenergy"}->{"by_minute"} } ) {
                    push @output, "ret_aenergy_by_minute_$arrayindex=$_";
                    $arrayindex++;
                }
            }

            print Dumper \@output;

            # Build filename using shelly's serial number, a random number (just in case), and the current timestamp
            my $filename = "data-$shelly_serial-" . int(rand(100_000)) . "." . (scalar time());

            my $timestamp = int $json->{"params"}->{"ts"} // time;
            my $perfstring = join ",", @output;
            my $metricstring = "model=$shelly_model,serial=$shelly_serial";
            $metricstring .= ",nickname=$nickname"  if  $nickname;
            my $outstring = "shellymqtt,$metricstring $perfstring $timestamp";

            print "$outstring\n";

            # Write string to file
            open OUTFILE, ">", "./spool/$filename"  or  die;
            print OUTFILE "$outstring\n";
            close OUTFILE;
        }

    }

    # Incoming message on topic shellypro1pm-xxxxxxxxxxxx/events/rpc is: {"src":"shellypro1pm-xxxxxxxxxxxx","dst":"shellypro1pm-xxxxxxxxxxxx/events","method":"NotifyStatus","params":{"ts":1779189000.00,"switch:0":{"aenergy":{"by_minute":[35.303,34.389,35.947],"minute_ts":1779189000,"total":5638.923},"apower":1.8,"aprtpower":1.8,"current":0.051,"freq":50.01,"pf":0.2,"ret_aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1779189000,"total":0.000},"voltage":234.7}}}
}