#!/bin/perl

use strict;
use warnings;

use LWP::UserAgent;
use Data::Dumper;


open INFILE, "<", "./spool/data-fcb467a6a0c4-97850.1779247260";
my $data = <INFILE>;
close INFILE;

print $data;


my $url = "http://localhost:8086/api/v2/write?org=none&bucket=mqttdata&precision=s";
my $token = "o7RFr6VJNEcAc0TFikNs9ke9KXkXmdC3oBc6oeMYmRhsoCmnRmiWPzBf7-dBTVLS__UoIYjmNEoAsyYUSXycdw==";


my $ua = LWP::UserAgent->new;
$ua->agent( "shelly-mqtt-to-influxdb" );

my $req = HTTP::Request->new( POST => $url );
$req->content_type( 'text/plain; charset=utf-8' );
$req->header( Accept => "application/json",
              Authorization => "Token $token"
);

$req->content( $data );

my $res = $ua->request( $req );

if ( $res->is_success ) {
    print $res->content;
}
else {
    print $res->status_line, "\n";
}

print "Code: " . $res->code . "\n";

#print Dumper \$res;